# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:17 # use latest PostgreSQL
    container_name: csp-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: csp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
